development:
  adapter: mysql
  database: photodepot_development
  username: username
  password: password
  host: 127.0.0.1

test:
  adapter: mysql
  database: photodepot_test
  username: username
  password: password
  host: 127.0.0.1

production:
  adapter: mysql
  database: photodepot_production
  username: username
  password: password
  host: 127.0.0.1
